name: Download full website

on:
  workflow_dispatch:
    inputs:
      site_url:
        description: "Введите ссылку на сайт (например https://example.com)"
        required: true
        default: "https://example.com"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install wget
        run: sudo apt-get update && sudo apt-get install -y wget

      - name: Download website (ONLY SAME DOMAIN)
        run: |
          mkdir site
          cd site

          URL="${{ github.event.inputs.site_url }}"
          DOMAIN=$(echo $URL | awk -F/ '{print $3}')

          echo "Downloading only domain: $DOMAIN"

          set +e
          wget \
            --mirror \
            --recursive \
            --level=inf \
            --convert-links \
            --adjust-extension \
            --page-requisites \
            --no-parent \
            --execute robots=off \
            --no-host-directories \
            --domains=$DOMAIN \
            --tries=3 \
            --timeout=30 \
            --wait=1 \
            --random-wait \
            --retry-connrefused \
            --user-agent="Mozilla/5.0" \
            "$URL"

          code=$?

          # Игнорируем exit code 8
          if [ $code -ne 0 ] && [ $code -ne 8 ]; then
            echo "Wget failed with real error code: $code"
            exit $code
          fi

          echo "Wget finished with code $code"

      - name: Upload site
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-site
          path: site
